package com.music.model;
// Generated Mar 5, 2017 9:57:18 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Genre generated by hbm2java
 */
@Entity
@Table(name="Genre"
    ,schema="dbo"
    ,catalog="MusicProject"
)
public class Genre  implements java.io.Serializable {


     private int id;
     private String name;
     private Set<Music> musics = new HashSet<Music>(0);

    public Genre() {
    }

	
    public Genre(int id) {
        this.id = id;
    }
    public Genre(int id, String name, Set<Music> musics) {
       this.id = id;
       this.name = name;
       this.musics = musics;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="Name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="genre")
    public Set<Music> getMusics() {
        return this.musics;
    }
    
    public void setMusics(Set<Music> musics) {
        this.musics = musics;
    }




}


