package com.music.model;
// Generated Mar 5, 2017 9:57:18 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Music generated by hbm2java
 */
@Entity
@Table(name="Music"
    ,schema="dbo"
    ,catalog="MusicProject"
)
public class Music  implements java.io.Serializable {


     private int id;
     private Album album;
     private Comment comment;
     private Genre genre;
     private Singer singer;
     private User user;
     private String name;
     private String image;
     private String link;
     private Boolean pending;

    public Music() {
    }

	
    public Music(int id) {
        this.id = id;
    }
    public Music(int id, Album album, Comment comment, Genre genre, Singer singer, User user, String name, String image, String link, Boolean pending) {
       this.id = id;
       this.album = album;
       this.comment = comment;
       this.genre = genre;
       this.singer = singer;
       this.user = user;
       this.name = name;
       this.image = image;
       this.link = link;
       this.pending = pending;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Album")
    public Album getAlbum() {
        return this.album;
    }
    
    public void setAlbum(Album album) {
        this.album = album;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CommentId")
    public Comment getComment() {
        return this.comment;
    }
    
    public void setComment(Comment comment) {
        this.comment = comment;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Genres")
    public Genre getGenre() {
        return this.genre;
    }
    
    public void setGenre(Genre genre) {
        this.genre = genre;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Singer")
    public Singer getSinger() {
        return this.singer;
    }
    
    public void setSinger(Singer singer) {
        this.singer = singer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Uploader")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="Name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Image")
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

    
    @Column(name="Link")
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }

    
    @Column(name="Pending")
    public Boolean getPending() {
        return this.pending;
    }
    
    public void setPending(Boolean pending) {
        this.pending = pending;
    }




}


