package com.music.model;
// Generated Mar 5, 2017 9:57:18 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Singer generated by hbm2java
 */
@Entity
@Table(name="Singer"
    ,schema="dbo"
    ,catalog="MusicProject"
)
public class Singer  implements java.io.Serializable {


     private int id;
     private Producer producer;
     private String fullname;
     private Date birthday;
     private String description;
     private Set<Music> musics = new HashSet<Music>(0);

    public Singer() {
    }

	
    public Singer(int id) {
        this.id = id;
    }
    public Singer(int id, Producer producer, String fullname, Date birthday, String description, Set<Music> musics) {
       this.id = id;
       this.producer = producer;
       this.fullname = fullname;
       this.birthday = birthday;
       this.description = description;
       this.musics = musics;
    }
   
     @Id 

    
    @Column(name="Id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Producer")
    public Producer getProducer() {
        return this.producer;
    }
    
    public void setProducer(Producer producer) {
        this.producer = producer;
    }

    
    @Column(name="Fullname")
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Birthday", length=23)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    
    @Column(name="Description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="singer")
    public Set<Music> getMusics() {
        return this.musics;
    }
    
    public void setMusics(Set<Music> musics) {
        this.musics = musics;
    }




}


